/********************************************************************************
** Form generated from reading UI file 'control_ui.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef CONTROL_UI_H
#define CONTROL_UI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ControlWindow
{
public:
    QAction *actionTest;
    QAction *actionMesh;
    QAction *actionAnimation;
    QAction *actionFramelist;
    QAction *actionScreenshot;
    QAction *actionExit;
    QAction *actionCamera;
    QWidget *centralwidget;
    QFrame *frame;
    QCheckBox *flowShow;
    QCheckBox *flowArrowsShow;
    QLabel *label;
    QSlider *flowFuture;
    QSlider *flowPast;
    QLabel *label_2;
    QLabel *label_3;
    QCheckBox *flowTranslation;
    QCheckBox *flowRotation;
    QCheckBox *flowObjects;
    QLineEdit *flowFutureText;
    QLineEdit *flowPastText;
    QCheckBox *flowFallback;
    QCheckBox *flowNormalize;
    QFrame *frame_2;
    QLabel *label_4;
    QCheckBox *depthShow;
    QLineEdit *depthScaleText;
    QLabel *label_25;
    QFrame *frame_3;
    QSplitter *splitter_2;
    QLabel *label_5;
    QCheckBox *renderedShow;
    QCheckBox *renderedVisibility;
    QFrame *frame_4;
    QSplitter *splitter_3;
    QLabel *label_6;
    QCheckBox *indexShow;
    QFrame *frame_5;
    QSplitter *splitter;
    QLabel *label_7;
    QCheckBox *positionShow;
    QCheckBox *positionShowCurser;
    QFrame *frame_6;
    QLabel *label_8;
    QSlider *generalFov;
    QLabel *label_9;
    QLabel *label_11;
    QSlider *generalSmoothing;
    QLineEdit *generalSmoothingText;
    QLineEdit *generalFovText;
    QCheckBox *checkBoxDepthTesting;
    QCheckBox *checkBoxCrop;
    QCheckBox *checkBoxIndirectRendering;
    QLabel *label_28;
    QSlider *generalMotionblur;
    QLineEdit *generalMotionblurText;
    QFrame *frame_7;
    QLabel *label_10;
    QPushButton *buttonNext;
    QPushButton *buttonPrev;
    QPushButton *buttonForward;
    QPushButton *buttonBackward;
    QPushButton *buttonStop;
    QLineEdit *lineEditFrame;
    QLabel *label_15;
    QLineEdit *lineEditFramesPerStep;
    QCheckBox *checkBoxRealtime;
    QLineEdit *lineEditFramesPerSecond;
    QLabel *label_16;
    QLabel *label_29;
    QLineEdit *lineEditSubframes;
    QComboBox *showOnlyFrames;
    QFrame *frame_8;
    QLabel *label_12;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *screenshotWidth;
    QLineEdit *screenshotHeight;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLineEdit *screenshotFilename;
    QComboBox *screenshotView;
    QPushButton *buttonSaveScreenshot;
    QComboBox *screenshotCamera;
    QCheckBox *screenshotPrerendering;
    QLabel *label_23;
    QFrame *frame_9;
    QLabel *label_13;
    QComboBox *performancePreresolution;
    QLabel *label_14;
    QLabel *label_22;
    QComboBox *performanceAnimation;
    QLabel *label_24;
    QComboBox *performanceDepthbuffer;
    QLabel *label_27;
    QComboBox *performanceCulling;
    QFrame *frame_10;
    QPushButton *buttonUpdateUi;
    QPushButton *buttonUpdateShader;
    QLineEdit *executeText;
    QPushButton *executeButton;
    QPushButton *buttonRedraw;
    QCheckBox *checkBoxGuiAutoupdate;
    QCheckBox *checkBoxDebug;
    QFrame *frame_11;
    QSplitter *splitter_4;
    QLabel *label_26;
    QCheckBox *showVisibility;
    QTableView *cameraTableView;
    QTableView *meshTableView;
    QFrame *frame_12;
    QSplitter *splitter_5;
    QLabel *label_30;
    QCheckBox *framelistsShow;
    QComboBox *coordinateSystem;
    QMenuBar *menubar;
    QMenu *menuFile;
    QMenu *menuImport;
    QMenu *menuExport;
    QMenu *menuScripts;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *ControlWindow)
    {
        if (ControlWindow->objectName().isEmpty())
            ControlWindow->setObjectName(QString::fromUtf8("ControlWindow"));
        ControlWindow->resize(484, 738);
        actionTest = new QAction(ControlWindow);
        actionTest->setObjectName(QString::fromUtf8("actionTest"));
        actionMesh = new QAction(ControlWindow);
        actionMesh->setObjectName(QString::fromUtf8("actionMesh"));
        actionAnimation = new QAction(ControlWindow);
        actionAnimation->setObjectName(QString::fromUtf8("actionAnimation"));
        actionFramelist = new QAction(ControlWindow);
        actionFramelist->setObjectName(QString::fromUtf8("actionFramelist"));
        actionScreenshot = new QAction(ControlWindow);
        actionScreenshot->setObjectName(QString::fromUtf8("actionScreenshot"));
        actionExit = new QAction(ControlWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionCamera = new QAction(ControlWindow);
        actionCamera->setObjectName(QString::fromUtf8("actionCamera"));
        centralwidget = new QWidget(ControlWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        frame = new QFrame(centralwidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 10, 461, 81));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        flowShow = new QCheckBox(frame);
        flowShow->setObjectName(QString::fromUtf8("flowShow"));
        flowShow->setGeometry(QRect(10, 30, 71, 23));
        flowArrowsShow = new QCheckBox(frame);
        flowArrowsShow->setObjectName(QString::fromUtf8("flowArrowsShow"));
        flowArrowsShow->setGeometry(QRect(10, 50, 71, 23));
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 10, 67, 17));
        flowFuture = new QSlider(frame);
        flowFuture->setObjectName(QString::fromUtf8("flowFuture"));
        flowFuture->setGeometry(QRect(80, 60, 71, 16));
        flowFuture->setMinimum(0);
        flowFuture->setMaximum(10);
        flowFuture->setValue(1);
        flowFuture->setOrientation(Qt::Horizontal);
        flowFuture->setInvertedAppearance(false);
        flowFuture->setInvertedControls(false);
        flowPast = new QSlider(frame);
        flowPast->setObjectName(QString::fromUtf8("flowPast"));
        flowPast->setGeometry(QRect(80, 30, 71, 16));
        flowPast->setMaximum(10);
        flowPast->setValue(1);
        flowPast->setOrientation(Qt::Horizontal);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(90, 10, 67, 17));
        label_3 = new QLabel(frame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(80, 40, 67, 17));
        flowTranslation = new QCheckBox(frame);
        flowTranslation->setObjectName(QString::fromUtf8("flowTranslation"));
        flowTranslation->setGeometry(QRect(220, 10, 91, 23));
        flowRotation = new QCheckBox(frame);
        flowRotation->setObjectName(QString::fromUtf8("flowRotation"));
        flowRotation->setGeometry(QRect(220, 30, 81, 23));
        flowObjects = new QCheckBox(frame);
        flowObjects->setObjectName(QString::fromUtf8("flowObjects"));
        flowObjects->setGeometry(QRect(220, 50, 91, 23));
        flowFutureText = new QLineEdit(frame);
        flowFutureText->setObjectName(QString::fromUtf8("flowFutureText"));
        flowFutureText->setGeometry(QRect(160, 50, 41, 21));
        flowPastText = new QLineEdit(frame);
        flowPastText->setObjectName(QString::fromUtf8("flowPastText"));
        flowPastText->setGeometry(QRect(160, 30, 41, 21));
        flowFallback = new QCheckBox(frame);
        flowFallback->setObjectName(QString::fromUtf8("flowFallback"));
        flowFallback->setGeometry(QRect(310, 10, 91, 23));
        flowNormalize = new QCheckBox(frame);
        flowNormalize->setObjectName(QString::fromUtf8("flowNormalize"));
        flowNormalize->setGeometry(QRect(310, 30, 91, 23));
        frame_2 = new QFrame(centralwidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(10, 100, 101, 81));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 10, 67, 17));
        depthShow = new QCheckBox(frame_2);
        depthShow->setObjectName(QString::fromUtf8("depthShow"));
        depthShow->setGeometry(QRect(10, 30, 71, 23));
        depthScaleText = new QLineEdit(frame_2);
        depthScaleText->setObjectName(QString::fromUtf8("depthScaleText"));
        depthScaleText->setGeometry(QRect(10, 50, 41, 16));
        label_25 = new QLabel(frame_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(60, 50, 31, 17));
        frame_3 = new QFrame(centralwidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(290, 100, 101, 81));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        splitter_2 = new QSplitter(frame_3);
        splitter_2->setObjectName(QString::fromUtf8("splitter_2"));
        splitter_2->setGeometry(QRect(10, 10, 73, 63));
        splitter_2->setOrientation(Qt::Vertical);
        label_5 = new QLabel(splitter_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        splitter_2->addWidget(label_5);
        renderedShow = new QCheckBox(splitter_2);
        renderedShow->setObjectName(QString::fromUtf8("renderedShow"));
        splitter_2->addWidget(renderedShow);
        renderedVisibility = new QCheckBox(splitter_2);
        renderedVisibility->setObjectName(QString::fromUtf8("renderedVisibility"));
        splitter_2->addWidget(renderedVisibility);
        frame_4 = new QFrame(centralwidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(210, 100, 71, 81));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        splitter_3 = new QSplitter(frame_4);
        splitter_3->setObjectName(QString::fromUtf8("splitter_3"));
        splitter_3->setGeometry(QRect(10, 10, 57, 40));
        splitter_3->setOrientation(Qt::Vertical);
        label_6 = new QLabel(splitter_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        splitter_3->addWidget(label_6);
        indexShow = new QCheckBox(splitter_3);
        indexShow->setObjectName(QString::fromUtf8("indexShow"));
        splitter_3->addWidget(indexShow);
        frame_5 = new QFrame(centralwidget);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(120, 100, 81, 81));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        splitter = new QSplitter(frame_5);
        splitter->setObjectName(QString::fromUtf8("splitter"));
        splitter->setGeometry(QRect(10, 10, 63, 63));
        splitter->setOrientation(Qt::Vertical);
        label_7 = new QLabel(splitter);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        splitter->addWidget(label_7);
        positionShow = new QCheckBox(splitter);
        positionShow->setObjectName(QString::fromUtf8("positionShow"));
        splitter->addWidget(positionShow);
        positionShowCurser = new QCheckBox(splitter);
        positionShowCurser->setObjectName(QString::fromUtf8("positionShowCurser"));
        splitter->addWidget(positionShowCurser);
        frame_6 = new QFrame(centralwidget);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(230, 490, 241, 131));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        label_8 = new QLabel(frame_6);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 10, 67, 17));
        generalFov = new QSlider(frame_6);
        generalFov->setObjectName(QString::fromUtf8("generalFov"));
        generalFov->setGeometry(QRect(80, 30, 101, 16));
        generalFov->setMaximum(180);
        generalFov->setValue(90);
        generalFov->setOrientation(Qt::Horizontal);
        label_9 = new QLabel(frame_6);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 30, 41, 17));
        label_11 = new QLabel(frame_6);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 50, 71, 17));
        generalSmoothing = new QSlider(frame_6);
        generalSmoothing->setObjectName(QString::fromUtf8("generalSmoothing"));
        generalSmoothing->setGeometry(QRect(80, 50, 101, 16));
        generalSmoothing->setMaximum(180);
        generalSmoothing->setValue(90);
        generalSmoothing->setOrientation(Qt::Horizontal);
        generalSmoothingText = new QLineEdit(frame_6);
        generalSmoothingText->setObjectName(QString::fromUtf8("generalSmoothingText"));
        generalSmoothingText->setGeometry(QRect(190, 50, 41, 21));
        generalFovText = new QLineEdit(frame_6);
        generalFovText->setObjectName(QString::fromUtf8("generalFovText"));
        generalFovText->setGeometry(QRect(190, 30, 41, 21));
        checkBoxDepthTesting = new QCheckBox(frame_6);
        checkBoxDepthTesting->setObjectName(QString::fromUtf8("checkBoxDepthTesting"));
        checkBoxDepthTesting->setGeometry(QRect(10, 100, 101, 23));
        checkBoxCrop = new QCheckBox(frame_6);
        checkBoxCrop->setObjectName(QString::fromUtf8("checkBoxCrop"));
        checkBoxCrop->setGeometry(QRect(10, 80, 101, 23));
        checkBoxIndirectRendering = new QCheckBox(frame_6);
        checkBoxIndirectRendering->setObjectName(QString::fromUtf8("checkBoxIndirectRendering"));
        checkBoxIndirectRendering->setGeometry(QRect(120, 80, 91, 23));
        label_28 = new QLabel(frame_6);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 70, 71, 17));
        generalMotionblur = new QSlider(frame_6);
        generalMotionblur->setObjectName(QString::fromUtf8("generalMotionblur"));
        generalMotionblur->setGeometry(QRect(80, 70, 101, 16));
        generalMotionblur->setMaximum(180);
        generalMotionblur->setValue(90);
        generalMotionblur->setOrientation(Qt::Horizontal);
        generalMotionblurText = new QLineEdit(frame_6);
        generalMotionblurText->setObjectName(QString::fromUtf8("generalMotionblurText"));
        generalMotionblurText->setGeometry(QRect(190, 70, 41, 21));
        frame_7 = new QFrame(centralwidget);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(10, 300, 161, 181));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        label_10 = new QLabel(frame_7);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 10, 51, 17));
        buttonNext = new QPushButton(frame_7);
        buttonNext->setObjectName(QString::fromUtf8("buttonNext"));
        buttonNext->setGeometry(QRect(100, 40, 21, 21));
        buttonPrev = new QPushButton(frame_7);
        buttonPrev->setObjectName(QString::fromUtf8("buttonPrev"));
        buttonPrev->setGeometry(QRect(40, 40, 21, 21));
        buttonForward = new QPushButton(frame_7);
        buttonForward->setObjectName(QString::fromUtf8("buttonForward"));
        buttonForward->setGeometry(QRect(130, 40, 21, 21));
        buttonBackward = new QPushButton(frame_7);
        buttonBackward->setObjectName(QString::fromUtf8("buttonBackward"));
        buttonBackward->setGeometry(QRect(10, 40, 21, 21));
        buttonStop = new QPushButton(frame_7);
        buttonStop->setObjectName(QString::fromUtf8("buttonStop"));
        buttonStop->setGeometry(QRect(68, 40, 21, 21));
        lineEditFrame = new QLineEdit(frame_7);
        lineEditFrame->setObjectName(QString::fromUtf8("lineEditFrame"));
        lineEditFrame->setGeometry(QRect(60, 10, 91, 21));
        label_15 = new QLabel(frame_7);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 80, 51, 17));
        lineEditFramesPerStep = new QLineEdit(frame_7);
        lineEditFramesPerStep->setObjectName(QString::fromUtf8("lineEditFramesPerStep"));
        lineEditFramesPerStep->setGeometry(QRect(90, 80, 61, 21));
        checkBoxRealtime = new QCheckBox(frame_7);
        checkBoxRealtime->setObjectName(QString::fromUtf8("checkBoxRealtime"));
        checkBoxRealtime->setGeometry(QRect(10, 60, 91, 23));
        lineEditFramesPerSecond = new QLineEdit(frame_7);
        lineEditFramesPerSecond->setObjectName(QString::fromUtf8("lineEditFramesPerSecond"));
        lineEditFramesPerSecond->setGeometry(QRect(90, 100, 61, 21));
        label_16 = new QLabel(frame_7);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 100, 71, 17));
        label_29 = new QLabel(frame_7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 120, 71, 17));
        lineEditSubframes = new QLineEdit(frame_7);
        lineEditSubframes->setObjectName(QString::fromUtf8("lineEditSubframes"));
        lineEditSubframes->setGeometry(QRect(90, 120, 61, 21));
        showOnlyFrames = new QComboBox(frame_7);
        showOnlyFrames->addItem(QString());
        showOnlyFrames->setObjectName(QString::fromUtf8("showOnlyFrames"));
        showOnlyFrames->setGeometry(QRect(10, 150, 141, 21));
        frame_8 = new QFrame(centralwidget);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(180, 300, 161, 181));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        label_12 = new QLabel(frame_8);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 10, 81, 17));
        label_17 = new QLabel(frame_8);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 30, 51, 17));
        label_18 = new QLabel(frame_8);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 50, 51, 17));
        screenshotWidth = new QLineEdit(frame_8);
        screenshotWidth->setObjectName(QString::fromUtf8("screenshotWidth"));
        screenshotWidth->setGeometry(QRect(80, 30, 71, 21));
        screenshotHeight = new QLineEdit(frame_8);
        screenshotHeight->setObjectName(QString::fromUtf8("screenshotHeight"));
        screenshotHeight->setGeometry(QRect(80, 50, 71, 21));
        label_19 = new QLabel(frame_8);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 70, 51, 17));
        label_20 = new QLabel(frame_8);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 90, 51, 17));
        label_21 = new QLabel(frame_8);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 110, 71, 17));
        screenshotFilename = new QLineEdit(frame_8);
        screenshotFilename->setObjectName(QString::fromUtf8("screenshotFilename"));
        screenshotFilename->setGeometry(QRect(80, 110, 71, 21));
        screenshotView = new QComboBox(frame_8);
        screenshotView->addItem(QString());
        screenshotView->addItem(QString());
        screenshotView->addItem(QString());
        screenshotView->addItem(QString());
        screenshotView->addItem(QString());
        screenshotView->setObjectName(QString::fromUtf8("screenshotView"));
        screenshotView->setGeometry(QRect(80, 90, 71, 21));
        buttonSaveScreenshot = new QPushButton(frame_8);
        buttonSaveScreenshot->setObjectName(QString::fromUtf8("buttonSaveScreenshot"));
        buttonSaveScreenshot->setGeometry(QRect(10, 150, 141, 21));
        screenshotCamera = new QComboBox(frame_8);
        screenshotCamera->setObjectName(QString::fromUtf8("screenshotCamera"));
        screenshotCamera->setGeometry(QRect(80, 70, 71, 21));
        screenshotPrerendering = new QCheckBox(frame_8);
        screenshotPrerendering->setObjectName(QString::fromUtf8("screenshotPrerendering"));
        screenshotPrerendering->setGeometry(QRect(100, 130, 21, 23));
        label_23 = new QLabel(frame_8);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 130, 71, 17));
        frame_9 = new QFrame(centralwidget);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(10, 490, 211, 121));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        label_13 = new QLabel(frame_9);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 10, 101, 17));
        performancePreresolution = new QComboBox(frame_9);
        performancePreresolution->addItem(QString());
        performancePreresolution->addItem(QString());
        performancePreresolution->addItem(QString());
        performancePreresolution->addItem(QString());
        performancePreresolution->addItem(QString());
        performancePreresolution->setObjectName(QString::fromUtf8("performancePreresolution"));
        performancePreresolution->setGeometry(QRect(120, 30, 86, 21));
        label_14 = new QLabel(frame_9);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 30, 101, 17));
        label_22 = new QLabel(frame_9);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 50, 61, 17));
        performanceAnimation = new QComboBox(frame_9);
        performanceAnimation->addItem(QString());
        performanceAnimation->addItem(QString());
        performanceAnimation->addItem(QString());
        performanceAnimation->setObjectName(QString::fromUtf8("performanceAnimation"));
        performanceAnimation->setGeometry(QRect(120, 50, 86, 21));
        label_24 = new QLabel(frame_9);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 70, 91, 17));
        performanceDepthbuffer = new QComboBox(frame_9);
        performanceDepthbuffer->addItem(QString());
        performanceDepthbuffer->addItem(QString());
        performanceDepthbuffer->addItem(QString());
        performanceDepthbuffer->setObjectName(QString::fromUtf8("performanceDepthbuffer"));
        performanceDepthbuffer->setGeometry(QRect(120, 70, 86, 21));
        label_27 = new QLabel(frame_9);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 90, 91, 17));
        performanceCulling = new QComboBox(frame_9);
        performanceCulling->addItem(QString());
        performanceCulling->addItem(QString());
        performanceCulling->addItem(QString());
        performanceCulling->addItem(QString());
        performanceCulling->setObjectName(QString::fromUtf8("performanceCulling"));
        performanceCulling->setGeometry(QRect(120, 90, 86, 21));
        frame_10 = new QFrame(centralwidget);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(10, 630, 461, 71));
        frame_10->setFrameShape(QFrame::StyledPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        buttonUpdateUi = new QPushButton(frame_10);
        buttonUpdateUi->setObjectName(QString::fromUtf8("buttonUpdateUi"));
        buttonUpdateUi->setGeometry(QRect(10, 10, 81, 21));
        buttonUpdateShader = new QPushButton(frame_10);
        buttonUpdateShader->setObjectName(QString::fromUtf8("buttonUpdateShader"));
        buttonUpdateShader->setGeometry(QRect(100, 10, 111, 21));
        executeText = new QLineEdit(frame_10);
        executeText->setObjectName(QString::fromUtf8("executeText"));
        executeText->setGeometry(QRect(10, 40, 231, 21));
        executeButton = new QPushButton(frame_10);
        executeButton->setObjectName(QString::fromUtf8("executeButton"));
        executeButton->setGeometry(QRect(250, 40, 71, 21));
        buttonRedraw = new QPushButton(frame_10);
        buttonRedraw->setObjectName(QString::fromUtf8("buttonRedraw"));
        buttonRedraw->setGeometry(QRect(220, 10, 71, 20));
        checkBoxGuiAutoupdate = new QCheckBox(frame_10);
        checkBoxGuiAutoupdate->setObjectName(QString::fromUtf8("checkBoxGuiAutoupdate"));
        checkBoxGuiAutoupdate->setGeometry(QRect(300, 10, 131, 23));
        checkBoxDebug = new QCheckBox(centralwidget);
        checkBoxDebug->setObjectName(QString::fromUtf8("checkBoxDebug"));
        checkBoxDebug->setGeometry(QRect(350, 370, 91, 23));
        frame_11 = new QFrame(centralwidget);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(400, 100, 71, 81));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        splitter_4 = new QSplitter(frame_11);
        splitter_4->setObjectName(QString::fromUtf8("splitter_4"));
        splitter_4->setGeometry(QRect(10, 10, 57, 40));
        splitter_4->setOrientation(Qt::Vertical);
        label_26 = new QLabel(splitter_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        splitter_4->addWidget(label_26);
        showVisibility = new QCheckBox(splitter_4);
        showVisibility->setObjectName(QString::fromUtf8("showVisibility"));
        splitter_4->addWidget(showVisibility);
        cameraTableView = new QTableView(centralwidget);
        cameraTableView->setObjectName(QString::fromUtf8("cameraTableView"));
        cameraTableView->setGeometry(QRect(240, 190, 231, 101));
        meshTableView = new QTableView(centralwidget);
        meshTableView->setObjectName(QString::fromUtf8("meshTableView"));
        meshTableView->setGeometry(QRect(10, 190, 221, 101));
        frame_12 = new QFrame(centralwidget);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setGeometry(QRect(350, 300, 121, 61));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Raised);
        splitter_5 = new QSplitter(frame_12);
        splitter_5->setObjectName(QString::fromUtf8("splitter_5"));
        splitter_5->setGeometry(QRect(10, 10, 101, 40));
        splitter_5->setOrientation(Qt::Vertical);
        label_30 = new QLabel(splitter_5);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        splitter_5->addWidget(label_30);
        framelistsShow = new QCheckBox(splitter_5);
        framelistsShow->setObjectName(QString::fromUtf8("framelistsShow"));
        splitter_5->addWidget(framelistsShow);
        coordinateSystem = new QComboBox(centralwidget);
        coordinateSystem->addItem(QString());
        coordinateSystem->addItem(QString());
        coordinateSystem->addItem(QString());
        coordinateSystem->addItem(QString());
        coordinateSystem->setObjectName(QString::fromUtf8("coordinateSystem"));
        coordinateSystem->setGeometry(QRect(350, 420, 121, 21));
        ControlWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(ControlWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 484, 20));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuImport = new QMenu(menuFile);
        menuImport->setObjectName(QString::fromUtf8("menuImport"));
        menuExport = new QMenu(menuFile);
        menuExport->setObjectName(QString::fromUtf8("menuExport"));
        menuScripts = new QMenu(menubar);
        menuScripts->setObjectName(QString::fromUtf8("menuScripts"));
        ControlWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(ControlWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        ControlWindow->setStatusBar(statusbar);
        QWidget::setTabOrder(buttonBackward, buttonStop);
        QWidget::setTabOrder(buttonStop, buttonForward);

        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuScripts->menuAction());
        menuFile->addAction(menuImport->menuAction());
        menuFile->addAction(menuExport->menuAction());
        menuFile->addAction(actionExit);
        menuImport->addAction(actionMesh);
        menuImport->addAction(actionAnimation);
        menuImport->addAction(actionFramelist);
        menuImport->addAction(actionCamera);
        menuExport->addAction(actionScreenshot);

        retranslateUi(ControlWindow);
        QObject::connect(buttonForward, SIGNAL(clicked()), ControlWindow, SLOT(playForward()));
        QObject::connect(buttonBackward, SIGNAL(clicked()), ControlWindow, SLOT(playBackward()));
        QObject::connect(buttonStop, SIGNAL(clicked()), ControlWindow, SLOT(playStop()));
        QObject::connect(depthShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showDepth(bool)));
        QObject::connect(indexShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showIndex(bool)));
        QObject::connect(positionShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showPosition(bool)));
        QObject::connect(renderedShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showRendered(bool)));
        QObject::connect(buttonPrev, SIGNAL(clicked()), ControlWindow, SLOT(prev()));
        QObject::connect(buttonNext, SIGNAL(clicked()), ControlWindow, SLOT(next()));
        QObject::connect(generalFov, SIGNAL(valueChanged(int)), ControlWindow, SLOT(fov(int)));
        QObject::connect(flowShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showFlow(bool)));
        QObject::connect(performancePreresolution, SIGNAL(currentIndexChanged(QString)), ControlWindow, SLOT(preresolution(QString)));
        QObject::connect(generalSmoothing, SIGNAL(valueChanged(int)), ControlWindow, SLOT(smoothing(int)));
        QObject::connect(flowPast, SIGNAL(valueChanged(int)), ControlWindow, SLOT(past(int)));
        QObject::connect(flowFuture, SIGNAL(valueChanged(int)), ControlWindow, SLOT(future(int)));
        QObject::connect(flowArrowsShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showArrows(bool)));
        QObject::connect(flowObjects, SIGNAL(toggled(bool)), ControlWindow, SLOT(flowObjects(bool)));
        QObject::connect(flowRotation, SIGNAL(toggled(bool)), ControlWindow, SLOT(flowRotation(bool)));
        QObject::connect(flowTranslation, SIGNAL(toggled(bool)), ControlWindow, SLOT(flowTranslation(bool)));
        QObject::connect(lineEditFrame, SIGNAL(textEdited(QString)), ControlWindow, SLOT(frame(QString)));
        QObject::connect(checkBoxRealtime, SIGNAL(toggled(bool)), ControlWindow, SLOT(realtime(bool)));
        QObject::connect(lineEditFramesPerSecond, SIGNAL(textEdited(QString)), ControlWindow, SLOT(framesPerSecond(QString)));
        QObject::connect(lineEditFramesPerStep, SIGNAL(textEdited(QString)), ControlWindow, SLOT(framesPerStep(QString)));
        QObject::connect(buttonSaveScreenshot, SIGNAL(clicked()), ControlWindow, SLOT(saveScreenshot()));
        QObject::connect(buttonUpdateUi, SIGNAL(clicked()), ControlWindow, SLOT(updateUi()));
        QObject::connect(buttonUpdateShader, SIGNAL(clicked()), ControlWindow, SLOT(updateShader()));
        QObject::connect(positionShowCurser, SIGNAL(toggled(bool)), ControlWindow, SLOT(positionShowCurser(bool)));
        QObject::connect(executeButton, SIGNAL(clicked()), ControlWindow, SLOT(executeCommand()));
        QObject::connect(executeText, SIGNAL(returnPressed()), ControlWindow, SLOT(executeCommand()));
        QObject::connect(ControlWindow, SIGNAL(updateUiSignal(int)), ControlWindow, SLOT(updateUi(int)));
        QObject::connect(buttonRedraw, SIGNAL(clicked()), ControlWindow, SLOT(redraw()));
        QObject::connect(performanceAnimation, SIGNAL(currentTextChanged(QString)), ControlWindow, SLOT(animating(QString)));
        QObject::connect(generalFovText, SIGNAL(textChanged(QString)), ControlWindow, SLOT(fov(QString)));
        QObject::connect(checkBoxDebug, SIGNAL(toggled(bool)), ControlWindow, SLOT(debug(bool)));
        QObject::connect(performanceDepthbuffer, SIGNAL(currentIndexChanged(QString)), ControlWindow, SLOT(depthbuffer(QString)));
        QObject::connect(depthScaleText, SIGNAL(textEdited(QString)), ControlWindow, SLOT(depthMax(QString)));
        QObject::connect(renderedVisibility, SIGNAL(toggled(bool)), ControlWindow, SLOT(renderedVisibility(bool)));
        QObject::connect(checkBoxDepthTesting, SIGNAL(toggled(bool)), ControlWindow, SLOT(depthTesting(bool)));
        QObject::connect(checkBoxGuiAutoupdate, SIGNAL(toggled(bool)), ControlWindow, SLOT(guiAutoUpdate(bool)));
        QObject::connect(performanceCulling, SIGNAL(currentIndexChanged(QString)), ControlWindow, SLOT(culling(QString)));
        QObject::connect(flowFallback, SIGNAL(toggled(bool)), ControlWindow, SLOT(flowFallback(bool)));
        QObject::connect(flowNormalize, SIGNAL(toggled(bool)), ControlWindow, SLOT(flowNormalize(bool)));
        QObject::connect(framelistsShow, SIGNAL(toggled(bool)), ControlWindow, SLOT(showFramelists(bool)));
        QObject::connect(checkBoxCrop, SIGNAL(toggled(bool)), ControlWindow, SLOT(crop(bool)));
        QObject::connect(generalSmoothingText, SIGNAL(textChanged(QString)), ControlWindow, SLOT(smoothing(QString)));
        QObject::connect(flowPastText, SIGNAL(textChanged(QString)), ControlWindow, SLOT(past(QString)));
        QObject::connect(flowFutureText, SIGNAL(textChanged(QString)), ControlWindow, SLOT(future(QString)));
        QObject::connect(actionMesh, SIGNAL(triggered()), ControlWindow, SLOT(importMesh()));
        QObject::connect(actionExit, SIGNAL(triggered()), ControlWindow, SLOT(exit()));
        QObject::connect(actionFramelist, SIGNAL(triggered()), ControlWindow, SLOT(importFramelist()));
        QObject::connect(actionCamera, SIGNAL(triggered()), ControlWindow, SLOT(addCamera()));
        QObject::connect(actionAnimation, SIGNAL(triggered()), ControlWindow, SLOT(importAnimation()));
        QObject::connect(coordinateSystem, SIGNAL(currentIndexChanged(QString)), ControlWindow, SLOT(coordinateSystem(QString)));
        QObject::connect(checkBoxIndirectRendering, SIGNAL(toggled(bool)), ControlWindow, SLOT(indirectRendering(bool)));
        QObject::connect(lineEditSubframes, SIGNAL(textEdited(QString)), ControlWindow, SLOT(subframes(QString)));
        QObject::connect(generalMotionblurText, SIGNAL(textEdited(QString)), ControlWindow, SLOT(motionBlur(QString)));
        QObject::connect(generalMotionblur, SIGNAL(valueChanged(int)), ControlWindow, SLOT(motionBlur(int)));
        QObject::connect(showVisibility, SIGNAL(toggled(bool)), ControlWindow, SLOT(showVisibility(bool)));
        QObject::connect(showOnlyFrames, SIGNAL(currentIndexChanged(QString)), ControlWindow, SLOT(showOnlyFrames(QString)));

        QMetaObject::connectSlotsByName(ControlWindow);
    } // setupUi

    void retranslateUi(QMainWindow *ControlWindow)
    {
        ControlWindow->setWindowTitle(QApplication::translate("ControlWindow", "MainWindow", nullptr));
        actionTest->setText(QApplication::translate("ControlWindow", "Test", nullptr));
        actionMesh->setText(QApplication::translate("ControlWindow", "Mesh", nullptr));
        actionAnimation->setText(QApplication::translate("ControlWindow", "Animation", nullptr));
        actionFramelist->setText(QApplication::translate("ControlWindow", "Framelist", nullptr));
        actionScreenshot->setText(QApplication::translate("ControlWindow", "Screenshot", nullptr));
        actionExit->setText(QApplication::translate("ControlWindow", "Exit", nullptr));
        actionCamera->setText(QApplication::translate("ControlWindow", "Camera", nullptr));
        flowShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        flowArrowsShow->setText(QApplication::translate("ControlWindow", "Arrows", nullptr));
        label->setText(QApplication::translate("ControlWindow", "Flow", nullptr));
        label_2->setText(QApplication::translate("ControlWindow", "Past", nullptr));
        label_3->setText(QApplication::translate("ControlWindow", "Future", nullptr));
        flowTranslation->setText(QApplication::translate("ControlWindow", "Translation", nullptr));
        flowRotation->setText(QApplication::translate("ControlWindow", "Rotation", nullptr));
        flowObjects->setText(QApplication::translate("ControlWindow", "Objects", nullptr));
        flowFallback->setText(QApplication::translate("ControlWindow", "Fallback", nullptr));
        flowNormalize->setText(QApplication::translate("ControlWindow", "Normalize", nullptr));
        label_4->setText(QApplication::translate("ControlWindow", "Depth", nullptr));
        depthShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        depthScaleText->setText(QApplication::translate("ControlWindow", "1", nullptr));
        label_25->setText(QApplication::translate("ControlWindow", "Dist", nullptr));
        label_5->setText(QApplication::translate("ControlWindow", "Rendered", nullptr));
        renderedShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        renderedVisibility->setText(QApplication::translate("ControlWindow", "Visibility", nullptr));
        label_6->setText(QApplication::translate("ControlWindow", "Index", nullptr));
        indexShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        label_7->setText(QApplication::translate("ControlWindow", "Position", nullptr));
        positionShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        positionShowCurser->setText(QApplication::translate("ControlWindow", "Curser", nullptr));
        label_8->setText(QApplication::translate("ControlWindow", "General", nullptr));
        label_9->setText(QApplication::translate("ControlWindow", "Fov", nullptr));
        label_11->setText(QApplication::translate("ControlWindow", "Smooting", nullptr));
        checkBoxDepthTesting->setText(QApplication::translate("ControlWindow", "DepthTesting", nullptr));
        checkBoxCrop->setText(QApplication::translate("ControlWindow", "Crop", nullptr));
        checkBoxIndirectRendering->setText(QApplication::translate("ControlWindow", "Indirect", nullptr));
        label_28->setText(QApplication::translate("ControlWindow", "Motionblur", nullptr));
        label_10->setText(QApplication::translate("ControlWindow", "Frame", nullptr));
        buttonNext->setText(QApplication::translate("ControlWindow", ">|", nullptr));
        buttonPrev->setText(QApplication::translate("ControlWindow", "|<", nullptr));
        buttonForward->setText(QApplication::translate("ControlWindow", ">", nullptr));
        buttonBackward->setText(QApplication::translate("ControlWindow", "<", nullptr));
        buttonStop->setText(QApplication::translate("ControlWindow", "H", nullptr));
        label_15->setText(QApplication::translate("ControlWindow", "F/Step", nullptr));
        lineEditFramesPerStep->setText(QApplication::translate("ControlWindow", "1", nullptr));
        checkBoxRealtime->setText(QApplication::translate("ControlWindow", "Realtime", nullptr));
        lineEditFramesPerSecond->setText(QApplication::translate("ControlWindow", "1", nullptr));
        label_16->setText(QApplication::translate("ControlWindow", "F/Second", nullptr));
        label_29->setText(QApplication::translate("ControlWindow", "Subframes", nullptr));
        lineEditSubframes->setText(QApplication::translate("ControlWindow", "1", nullptr));
        showOnlyFrames->setItemText(0, QApplication::translate("ControlWindow", "All", nullptr));

        label_12->setText(QApplication::translate("ControlWindow", "Screenshot", nullptr));
        label_17->setText(QApplication::translate("ControlWindow", "Width", nullptr));
        label_18->setText(QApplication::translate("ControlWindow", "Height", nullptr));
        screenshotWidth->setText(QApplication::translate("ControlWindow", "1024", nullptr));
        screenshotHeight->setText(QApplication::translate("ControlWindow", "1024", nullptr));
        label_19->setText(QApplication::translate("ControlWindow", "Camera", nullptr));
        label_20->setText(QApplication::translate("ControlWindow", "View", nullptr));
        label_21->setText(QApplication::translate("ControlWindow", "Filename", nullptr));
        screenshotView->setItemText(0, QApplication::translate("ControlWindow", "Rendered", nullptr));
        screenshotView->setItemText(1, QApplication::translate("ControlWindow", "Position", nullptr));
        screenshotView->setItemText(2, QApplication::translate("ControlWindow", "Flow", nullptr));
        screenshotView->setItemText(3, QApplication::translate("ControlWindow", "Index", nullptr));
        screenshotView->setItemText(4, QApplication::translate("ControlWindow", "Depth", nullptr));

        buttonSaveScreenshot->setText(QApplication::translate("ControlWindow", "Save", nullptr));
        screenshotPrerendering->setText(QString());
        label_23->setText(QApplication::translate("ControlWindow", "Pre", nullptr));
        label_13->setText(QApplication::translate("ControlWindow", "Performance", nullptr));
        performancePreresolution->setItemText(0, QApplication::translate("ControlWindow", "256", nullptr));
        performancePreresolution->setItemText(1, QApplication::translate("ControlWindow", "512", nullptr));
        performancePreresolution->setItemText(2, QApplication::translate("ControlWindow", "1024", nullptr));
        performancePreresolution->setItemText(3, QApplication::translate("ControlWindow", "2048", nullptr));
        performancePreresolution->setItemText(4, QApplication::translate("ControlWindow", "4096", nullptr));

        label_14->setText(QApplication::translate("ControlWindow", "Preresolution", nullptr));
        label_22->setText(QApplication::translate("ControlWindow", "Redraw", nullptr));
        performanceAnimation->setItemText(0, QApplication::translate("ControlWindow", "Always", nullptr));
        performanceAnimation->setItemText(1, QApplication::translate("ControlWindow", "Automatic", nullptr));
        performanceAnimation->setItemText(2, QApplication::translate("ControlWindow", "Manual", nullptr));

        label_24->setText(QApplication::translate("ControlWindow", "Depthbuffer", nullptr));
        performanceDepthbuffer->setItemText(0, QApplication::translate("ControlWindow", "16 bit", nullptr));
        performanceDepthbuffer->setItemText(1, QApplication::translate("ControlWindow", "24 bit", nullptr));
        performanceDepthbuffer->setItemText(2, QApplication::translate("ControlWindow", "32 bit", nullptr));

        label_27->setText(QApplication::translate("ControlWindow", "Culling", nullptr));
        performanceCulling->setItemText(0, QApplication::translate("ControlWindow", "None", nullptr));
        performanceCulling->setItemText(1, QApplication::translate("ControlWindow", "Front", nullptr));
        performanceCulling->setItemText(2, QApplication::translate("ControlWindow", "Back", nullptr));
        performanceCulling->setItemText(3, QApplication::translate("ControlWindow", "Front and Back", nullptr));

        buttonUpdateUi->setText(QApplication::translate("ControlWindow", "UpdateUi", nullptr));
        buttonUpdateShader->setText(QApplication::translate("ControlWindow", "UpdateShader", nullptr));
        executeButton->setText(QApplication::translate("ControlWindow", "Execute", nullptr));
        buttonRedraw->setText(QApplication::translate("ControlWindow", "Redraw", nullptr));
        checkBoxGuiAutoupdate->setText(QApplication::translate("ControlWindow", "Gui Autoupdate", nullptr));
        checkBoxDebug->setText(QApplication::translate("ControlWindow", "Debug", nullptr));
        label_26->setText(QApplication::translate("ControlWindow", "Visibility", nullptr));
        showVisibility->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        label_30->setText(QApplication::translate("ControlWindow", "Framelists", nullptr));
        framelistsShow->setText(QApplication::translate("ControlWindow", "Show", nullptr));
        coordinateSystem->setItemText(0, QApplication::translate("ControlWindow", "Spherical Multipass", nullptr));
        coordinateSystem->setItemText(1, QApplication::translate("ControlWindow", "Spherical Singlepass", nullptr));
        coordinateSystem->setItemText(2, QApplication::translate("ControlWindow", "Spherical Approximated", nullptr));
        coordinateSystem->setItemText(3, QApplication::translate("ControlWindow", "Equirectangular", nullptr));

        menuFile->setTitle(QApplication::translate("ControlWindow", "Fi&le", nullptr));
        menuImport->setTitle(QApplication::translate("ControlWindow", "Add", nullptr));
        menuExport->setTitle(QApplication::translate("ControlWindow", "Export", nullptr));
        menuScripts->setTitle(QApplication::translate("ControlWindow", "Scripts", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ControlWindow: public Ui_ControlWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // CONTROL_UI_H
