name: C++ Ci with Qt

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Install Qt
#      uses: jurplel/install-qt-action@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name:    
      run: sudo apt-get update && sudo apt-get install qt5-qmake qtbase5-dev qtchooser qtbase5-dev-tools libopenexr-dev libpng-dev -y && sudo /sbin/ldconfig -v
    - name: fast-float
      run: git clone https://github.com/fastfloat/fast_float.git
    - name: Install Python-dependencies
      run: sudo apt-get install python3-dev python3-pip -y && python3 -m pip install --upgrade pip; pip3 install numpy imageio pyexr OpenEXR
    - name: Build with Make
      run: make -j test
    - name: Install xvfb
      run: sudo apt-get install xvfb -y
    - name: Run OpenGl-Tests
      run: export LD_LIBRARY_PATH=$(pwd)/libgl-xlib; cd test; xvfb-run make all
